package ChatApp;


/**
* ChatApp/ChatCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 8 mars 2016 kl 19:22 CET
*/

public interface ChatCallbackOperations 
{
  void callback (String message);
} // interface ChatCallbackOperations
