package ChatApp;


/**
* ChatApp/ChatCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Wednesday, 9 March 2016 10:03:51 o'clock CET
*/

public interface ChatCallbackOperations 
{
  void callback (String message);
} // interface ChatCallbackOperations
