package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 8 mars 2016 kl 19:22 CET
*/

public interface ChatOperations 
{
  String say (ChatApp.ChatCallback objref, String message);
  void join (ChatApp.ChatCallback objref, String username);
  void list (ChatApp.ChatCallback objref);
  void leave (ChatApp.ChatCallback objref);
  void post (ChatApp.ChatCallback objref, String msg);
  void quit (ChatApp.ChatCallback objref);
  void game (ChatApp.ChatCallback objref, String data);
} // interface ChatOperations
